[2024-01-21T13:46:10.085+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: primeira_dag.tsk1 __airflow_temporary_run_2024-01-21T13:46:09.792850+00:00__ [queued]>
[2024-01-21T13:46:10.090+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: primeira_dag.tsk1 __airflow_temporary_run_2024-01-21T13:46:09.792850+00:00__ [queued]>
[2024-01-21T13:46:10.090+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-21T13:46:10.090+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-21T13:46:10.090+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-21T13:46:10.097+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-01-21 00:00:00+00:00
[2024-01-21T13:46:10.100+0000] {standard_task_runner.py:55} INFO - Started process 2288 to run task
[2024-01-21T13:46:10.101+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'primeira_dag', 'tsk1', '__***_temporary_run_2024-01-21T13:46:09.792850+00:00__', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/01-primeira-dag.py', '--cfg-path', '/tmp/tmpwm_mfrny']
[2024-01-21T13:46:10.102+0000] {standard_task_runner.py:83} INFO - Job 157: Subtask tsk1
[2024-01-21T13:46:10.133+0000] {task_command.py:388} INFO - Running <TaskInstance: primeira_dag.tsk1 __airflow_temporary_run_2024-01-21T13:46:09.792850+00:00__ [running]> on host cb9489d15b76
[2024-01-21T13:46:10.165+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=primeira_dag
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-01-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=__***_temporary_run_2024-01-21T13:46:09.792850+00:00__
[2024-01-21T13:46:10.166+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-21T13:46:10.166+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sleep 5']
[2024-01-21T13:46:10.171+0000] {subprocess.py:86} INFO - Output:
[2024-01-21T13:46:15.175+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-21T13:46:15.198+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 211, in set
    raise ValueError(f"DAG run not found on DAG {dag_id!r} with ID {run_id!r}")
ValueError: DAG run not found on DAG 'primeira_dag' with ID '__***_temporary_run_2024-01-21T13:46:09.792850+00:00__'
[2024-01-21T13:46:15.213+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=primeira_dag, task_id=tsk1, execution_date=20240121T000000, start_date=20240121T134610, end_date=20240121T134615
[2024-01-21T13:46:15.236+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 157 for task tsk1 ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(primeira_dag, tsk1, __airflow_temporary_run_2024-01-21T13:46:09.792850+00:00__, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'tsk1', 'dag_id': 'primeira_dag', 'run_id': '__airflow_temporary_run_2024-01-21T13:46:09.792850+00:00__', 'map_index': -1, 'start_date': datetime.datetime(2024, 1, 21, 13, 46, 10, 86296, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 1, 21, 13, 46, 15, 211597, tzinfo=Timezone('UTC')), 'duration': 5}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 2288)
[2024-01-21T13:46:15.257+0000] {local_task_job.py:208} INFO - Task exited with return code 1
