[2024-01-19T01:24:53.889+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: producer.t1 manual__2024-01-19T01:24:51.166573+00:00 [queued]>
[2024-01-19T01:24:53.911+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: producer.t1 manual__2024-01-19T01:24:51.166573+00:00 [queued]>
[2024-01-19T01:24:53.912+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-19T01:24:53.912+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-19T01:24:53.912+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-19T01:24:53.923+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): t1> on 2024-01-19 01:24:51.166573+00:00
[2024-01-19T01:24:53.931+0000] {standard_task_runner.py:55} INFO - Started process 23760 to run task
[2024-01-19T01:24:53.934+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'producer', 't1', 'manual__2024-01-19T01:24:51.166573+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/20-producer.py', '--cfg-path', '/tmp/tmp7z4ycrkv']
[2024-01-19T01:24:53.936+0000] {standard_task_runner.py:83} INFO - Job 113: Subtask t1
[2024-01-19T01:24:53.978+0000] {task_command.py:388} INFO - Running <TaskInstance: producer.t1 manual__2024-01-19T01:24:51.166573+00:00 [running]> on host cb9489d15b76
[2024-01-19T01:24:54.028+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=producer
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2024-01-19T01:24:51.166573+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-19T01:24:51.166573+00:00
[2024-01-19T01:24:54.062+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/20-producer.py", line 14, in my_file
    dataset = pd.read_csv("opt/airflow/data/Churn.csv", sep=";")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/data/Churn.csv'
[2024-01-19T01:24:54.093+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=producer, task_id=t1, execution_date=20240119T012451, start_date=20240119T012453, end_date=20240119T012454
[2024-01-19T01:24:54.106+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 113 for task t1 ([Errno 2] No such file or directory: 'opt/airflow/data/Churn.csv'; 23760)
[2024-01-19T01:24:54.120+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-19T01:24:54.136+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
