[2024-01-20T02:20:01.233+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bancodedados.create_table manual__2024-01-20T02:19:58.668461+00:00 [queued]>
[2024-01-20T02:20:01.262+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bancodedados.create_table manual__2024-01-20T02:19:58.668461+00:00 [queued]>
[2024-01-20T02:20:01.262+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-20T02:20:01.263+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-20T02:20:01.263+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-20T02:20:01.275+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_table> on 2024-01-20 02:19:58.668461+00:00
[2024-01-20T02:20:01.284+0000] {standard_task_runner.py:55} INFO - Started process 49468 to run task
[2024-01-20T02:20:01.288+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bancodedados', 'create_table', 'manual__2024-01-20T02:19:58.668461+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/23-bancodedados.py', '--cfg-path', '/tmp/tmp07tyk28n']
[2024-01-20T02:20:01.288+0000] {standard_task_runner.py:83} INFO - Job 122: Subtask create_table
[2024-01-20T02:20:01.328+0000] {task_command.py:388} INFO - Running <TaskInstance: bancodedados.create_table manual__2024-01-20T02:19:58.668461+00:00 [running]> on host cb9489d15b76
[2024-01-20T02:20:01.395+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bancodedados
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-01-20T02:19:58.668461+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-20T02:19:58.668461+00:00
[2024-01-20T02:20:01.396+0000] {sql.py:254} INFO - Executing: create table if not exists teste(id int);
[2024-01-20T02:20:01.403+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2024-01-20T02:20:01.684+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2024-01-20T02:20:01.690+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "***"

[2024-01-20T02:20:01.715+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=bancodedados, task_id=create_table, execution_date=20240120T021958, start_date=20240120T022001, end_date=20240120T022001
[2024-01-20T02:20:01.822+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 122 for task create_table (FATAL:  password authentication failed for user "***"
; 49468)
[2024-01-20T02:20:01.875+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-20T02:20:01.977+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
