[2024-01-20T02:55:09.457+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: hook.print_data_task manual__2024-01-20T02:55:05.601378+00:00 [queued]>
[2024-01-20T02:55:09.461+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: hook.print_data_task manual__2024-01-20T02:55:05.601378+00:00 [queued]>
[2024-01-20T02:55:09.462+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-20T02:55:09.462+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-20T02:55:09.462+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-20T02:55:09.467+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): print_data_task> on 2024-01-20 02:55:05.601378+00:00
[2024-01-20T02:55:09.470+0000] {standard_task_runner.py:55} INFO - Started process 52452 to run task
[2024-01-20T02:55:09.472+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'hook', 'print_data_task', 'manual__2024-01-20T02:55:05.601378+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/24-hooks.py', '--cfg-path', '/tmp/tmpdpmh620l']
[2024-01-20T02:55:09.472+0000] {standard_task_runner.py:83} INFO - Job 143: Subtask print_data_task
[2024-01-20T02:55:09.513+0000] {task_command.py:388} INFO - Running <TaskInstance: hook.print_data_task manual__2024-01-20T02:55:05.601378+00:00 [running]> on host cb9489d15b76
[2024-01-20T02:55:09.546+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hook
AIRFLOW_CTX_TASK_ID=print_data_task
AIRFLOW_CTX_EXECUTION_DATE=2024-01-20T02:55:05.601378+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-20T02:55:05.601378+00:00
[2024-01-20T02:55:09.552+0000] {logging_mixin.py:137} INFO - Dados na tabela:
[2024-01-20T02:55:09.552+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/24-hooks.py", line 28, in print_data
    for row in task_instance:
TypeError: 'NoneType' object is not iterable
[2024-01-20T02:55:09.557+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=hook, task_id=print_data_task, execution_date=20240120T025505, start_date=20240120T025509, end_date=20240120T025509
[2024-01-20T02:55:09.562+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 143 for task print_data_task ('NoneType' object is not iterable; 52452)
[2024-01-20T02:55:09.610+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-20T02:55:09.620+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
