[2024-01-09T20:26:33.686+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdagallfailed.tsk2 manual__2024-01-09T20:26:32.815967+00:00 [queued]>
[2024-01-09T20:26:33.717+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdagallfailed.tsk2 manual__2024-01-09T20:26:32.815967+00:00 [queued]>
[2024-01-09T20:26:33.719+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-09T20:26:33.719+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-09T20:26:33.745+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-09T20:26:33.780+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk2> on 2024-01-09 20:26:32.815967+00:00
[2024-01-09T20:26:33.784+0000] {standard_task_runner.py:55} INFO - Started process 47444 to run task
[2024-01-09T20:26:33.787+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdagallfailed', 'tsk2', 'manual__2024-01-09T20:26:32.815967+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/7-trigger-dag.py', '--cfg-path', '/tmp/tmp6a9xsnhy']
[2024-01-09T20:26:33.788+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask tsk2
[2024-01-09T20:26:33.842+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdagallfailed.tsk2 manual__2024-01-09T20:26:32.815967+00:00 [running]> on host 8c81727a976c
[2024-01-09T20:26:33.929+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdagallfailed
AIRFLOW_CTX_TASK_ID=tsk2
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T20:26:32.815967+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-09T20:26:32.815967+00:00
[2024-01-09T20:26:33.930+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-09T20:26:33.931+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-01-09T20:26:33.938+0000] {subprocess.py:86} INFO - Output:
[2024-01-09T20:26:33.939+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-09T20:26:33.950+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-09T20:26:33.959+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerdagallfailed, task_id=tsk2, execution_date=20240109T202632, start_date=20240109T202633, end_date=20240109T202633
[2024-01-09T20:26:33.972+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 29 for task tsk2 (Bash command failed. The command returned a non-zero exit code 1.; 47444)
[2024-01-09T20:26:34.000+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-09T20:26:34.012+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
