[2024-01-09T20:24:02.486+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdagfailed.tsk1 manual__2024-01-09T20:24:01.793607+00:00 [queued]>
[2024-01-09T20:24:02.492+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdagfailed.tsk1 manual__2024-01-09T20:24:01.793607+00:00 [queued]>
[2024-01-09T20:24:02.492+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-09T20:24:02.492+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-09T20:24:02.492+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-09T20:24:02.499+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-01-09 20:24:01.793607+00:00
[2024-01-09T20:24:02.502+0000] {standard_task_runner.py:55} INFO - Started process 47206 to run task
[2024-01-09T20:24:02.507+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdagfailed', 'tsk1', 'manual__2024-01-09T20:24:01.793607+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/6-trigger-dag.py', '--cfg-path', '/tmp/tmp4dfmvswb']
[2024-01-09T20:24:02.507+0000] {standard_task_runner.py:83} INFO - Job 24: Subtask tsk1
[2024-01-09T20:24:02.558+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdagfailed.tsk1 manual__2024-01-09T20:24:01.793607+00:00 [running]> on host 8c81727a976c
[2024-01-09T20:24:02.603+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdagfailed
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T20:24:01.793607+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-09T20:24:01.793607+00:00
[2024-01-09T20:24:02.604+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-09T20:24:02.604+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-01-09T20:24:02.612+0000] {subprocess.py:86} INFO - Output:
[2024-01-09T20:24:02.614+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-09T20:24:02.620+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-09T20:24:02.628+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerdagfailed, task_id=tsk1, execution_date=20240109T202401, start_date=20240109T202402, end_date=20240109T202402
[2024-01-09T20:24:02.635+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 24 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 47206)
[2024-01-09T20:24:02.640+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-09T20:24:02.651+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
