[2024-01-09T20:26:33.686+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdagallfailed.tsk1 manual__2024-01-09T20:26:32.815967+00:00 [queued]>
[2024-01-09T20:26:33.706+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdagallfailed.tsk1 manual__2024-01-09T20:26:32.815967+00:00 [queued]>
[2024-01-09T20:26:33.709+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-09T20:26:33.709+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-09T20:26:33.712+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-09T20:26:33.767+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-01-09 20:26:32.815967+00:00
[2024-01-09T20:26:33.772+0000] {standard_task_runner.py:55} INFO - Started process 47443 to run task
[2024-01-09T20:26:33.776+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdagallfailed', 'tsk1', 'manual__2024-01-09T20:26:32.815967+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/7-trigger-dag.py', '--cfg-path', '/tmp/tmp_nvi6oz7']
[2024-01-09T20:26:33.777+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask tsk1
[2024-01-09T20:26:33.825+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdagallfailed.tsk1 manual__2024-01-09T20:26:32.815967+00:00 [running]> on host 8c81727a976c
[2024-01-09T20:26:33.911+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdagallfailed
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T20:26:32.815967+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-09T20:26:32.815967+00:00
[2024-01-09T20:26:33.913+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-09T20:26:33.915+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-01-09T20:26:33.926+0000] {subprocess.py:86} INFO - Output:
[2024-01-09T20:26:33.928+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-09T20:26:33.937+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-09T20:26:33.940+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerdagallfailed, task_id=tsk1, execution_date=20240109T202632, start_date=20240109T202633, end_date=20240109T202633
[2024-01-09T20:26:33.958+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 47443)
[2024-01-09T20:26:33.988+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-01-09T20:26:34.002+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
